### ISSUE TITLE
Unable to evaluate multiple lines

### ISSUE THREAD

**Issue by skippednote** [hung-phan/babel-repl#2] opened 2015-08-26 01:35 UTC
I tried to send the following snippet to babel-repl but it evaluates the first line only.

``` js
[1,2,3,4,5].map(item => {
  return item * item
});
```

I tried with paragraph, current buffer, and current region but no luck.

Also do you have any keybinding recommendation for these or how to hook this up with js2-mode.

**Comment by hung-phan** [comment] 2015-08-26 03:01
Actually the problem is from babel-node itself. You can follow it here: `https://github.com/babel/babel/issues/1741`. I am still waiting for it to be merged. `https://github.com/joyent/node/pull/25587`. Then, it will just work

**Comment by CestDiego** [comment] 2015-11-25 19:43
How is the status on this? :( seems babel doesn't have issues anymore.

**Comment by ghost** [comment] 2016-01-13 20:42
Is this fixed yet? :(

**Comment by hung-phan** [comment] 2016-01-14 17:55
Not yet :sweat_smile:. Still have the problem when trying to run babel-node with multiple lines.
![interaction](https://cloud.githubusercontent.com/assets/3093244/12332713/aa38acf6-bb22-11e5-860c-8cade184696c.gif).

**Comment by hung-phan** [comment] 2016-01-14 17:57
A solution is that we will replace all new line characters before sending them to babel-node buffer.

**Comment by hung-phan** [comment] 2016-01-14 17:57
But this will break readability. :smile:

**Comment by hung-phan** [comment] 2016-01-14 18:11
https://github.com/hung-phan/babel-repl/commit/b198fa05edc8bef06b07ad8a5bac9a35544f9ea6

**Closed as completed** 2016-01-14 18:11 UTC

**Comment by k-ode** [comment] 2016-01-22 09:38
This does still not work for me on Windows 8 with Emacs 24.4.

How unfortunate that they seem to be unwilling to fix this on the nodejs side.

**Comment by ghost** [comment] 2016-01-22 16:19
@hung-phan Thanks a lot for the workaround. At least it's usable now. I tried to keep track of progress on the repl issue at node upstream. But unfortunately this doesn't seem to have much priority there.

**Comment by hung-phan** [comment] 2016-01-23 02:50
Uhm, the only thing it will cause the problem right now is that if you have a comment `//` in your code. I also want them to fix it on the node.js side 😞
